"""add conversation summary

Revision ID: bf7e23f4d76b
Revises: a40ce2b2c084
Create Date: 2026-07-30 01:01:10.978514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7e23f4d76b'
down_revision: Union[str, Sequence[str], None] = 'a40ce2b2c084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
